BEGIN;

DROP TABLE IF EXISTS theme;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS message;

CREATE TABLE theme (
    theme_id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE users (
    chat_id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    ref VARCHAR(250) NOT NULL,
    theme_id INT NOT NULL REFERENCES theme(theme_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE message (
    id SERIAL PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES users(chat_id) ON DELETE CASCADE ON UPDATE CASCADE,
    theme_id INT NOT NULL REFERENCES theme(theme_id) ON DELETE CASCADE ON UPDATE CASCADE,
    message TEXT NOT NULL,
    time VARCHAR(250) NOT NULL,
    ref VARCHAR(250) NOT NULL
);

COMMIT;